import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useMemo } from "react";
import ThreadComp from "../../../components/threadPage";

const ThreadPage: NextPage = () => {
    const router = useRouter();

    const boardName = useMemo(() => typeof router.query.boardName === "string" ? router.query.boardName : "", [router.query.boardName]);
    const threadId = useMemo(() => typeof router.query.threadId === "string" ? router.query.threadId : "", [router.query.threadId]);

    return (
        <>
            <Head>
                <title>Boards</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!!boardName && !!threadId ? <ThreadComp boardName={boardName} threadId={threadId} /> : null}
        </>
    );
};

export default ThreadPage;