import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useMemo } from "react";
import BoardComp from "../../components/boardPage";

const BoardPage: NextPage = () => {
    const router = useRouter();

    const boardName = useMemo(() => typeof router.query.boardName === "string" ? router.query.boardName : "", [router.query.boardName]);
    const pageNum = useMemo(() => +(router.query.pageNum || "0") || 0, [router.query.pageNum]);

    return (
        <>
            <Head>
                <title>Boards</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!!boardName && !!pageNum ? <BoardComp boardName={boardName} pageNum={pageNum} /> : null}
        </>
    );
};

export default BoardPage;