import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useMemo } from "react";
import BoardComp from "../../components/boardPage";

const BoardIndex: NextPage = () => {
    const router = useRouter();

    const boardName = useMemo(() => typeof router.query.boardName === "string" ? router.query.boardName : "", [router.query.boardName]);

    return (
        <>
            <Head>
                <title>Boards</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!!boardName ? <BoardComp boardName={boardName} pageNum={1} /> : null}
        </>
    );
};

export default BoardIndex;